language: node_js
node_js:
  - "5.0"
  - "4.1"
  - "4.0"
cache:
  directories:
    - "node_modules"
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gulp-plugin' ]; then cd .. && eval "mv $currentfolder generator-gulp-plugin" && cd generator-gulp-plugin; fi
